### ISSUE TITLE
Doesn't work with Writables

### ISSUE THREAD

**Issue by apowers313** [gulpjs/lead#3]
This code:
``` js
const lead = require("lead");
const { Writable } = require("stream");

let ws = new Writable({ write: () => {} });
lead(ws);
```

Causes error:
> TypeError: Cannot read property 'objectMode' of undefined
    at sink (/Users/ampower/WorkDocs/Projects/proto/lead-bug/node_modules/lead/index.js:21:39)

Suggest changing [this line](https://github.com/gulpjs/lead/blob/e82a4a3847fd912d2a125fc61a590a5423f3b0b6/index.js#L21) to:

``` js
  var sinkOptions = {
    objectMode: stream._writableState.objectMode,
  };
```

**Comment by phated** [comment]
How backward compatible is that property?

**Comment by phated** [comment]
Wait, you aren't supposed to use this with a Writeable stream. They already sink themselves.

**Comment by apowers313** [comment]
Documentation for this module says:

> Sets up event listeners to infer if the stream is being used as a Transform or Writeable stream and sinks it on nextTick if necessary.

And my inference was this was used to guarantee that a stream was sunk, whether it was a Transform or Writable.

The referenced property above goes back to at least [October 2012](https://github.com/nodejs/node/commit/420e07c5777bdb2e493147d296abfc102f725015#diff-1915a7b992a3012b177dd855fa3477e0R51) and probably further -- it's the same property that is defined for readable streams, but for writable streams. It also works the same for Duplex and Transform streams, since Duplex copies over the properties of a Writable stream as a [parasitic inheritance](https://github.com/nodejs/node/blob/master/lib/_stream_duplex.js#L24-L25).

Also, it just generally makes more sense to reference the writable side of the stream since a Duplex stream may have configured them independently.

**Comment by phated** [comment]
The docs reference making a Transform stream being used as a Writeable stream (as a bunch of gulp plugins try to do), not passing a Writeable stream. A Writeable stream already drains itself.
