### ISSUE TITLE
Strange ordering when argument is `streamx`

### ISSUE THREAD

**Issue by coreyfarrell** [gulpjs/lead#5]
Create and run the following script within a git clone of `lead`.
```js
'use strict';

var expect = require('expect');
var lead = require('.');
var miss = require('mississippi');

function runTest (stream) {
  return new Promise(function (resolve, reject) {
    var readables = 0;
    var write = lead(stream);
    write.on('readable', function () {
      while (this.read()) {
        readables++;
        console.log('read');
      }
    });

    miss.pipe([miss.from.obj([{}]), write], function (err) {
      console.log('done');
      if (err) {
        reject(err);
      } else {
        resolve();
      }
    });
  });
}

console.log('Test streamx:');
runTest(new (require('streamx').PassThrough)())
  .then(function () {
    console.log('\nTest stream:');
    return runTest(new (require('stream').PassThrough)({objectMode: true}));
  })
  .then(function () {
    console.log('\nTest readable-stream:');
    runTest(new (require('readable-stream').PassThrough)({objectMode: true}));
  });
```

### What were you expecting to happen?
Each call to runTest should print `read` before `done`.

### What actually happened?
The runTest using a `streamx` object prints `done` before `read`.  This is likely a `streamx` issue but I still wanted to post here.  The `stream` and `readable-stream` tests work as expected.

Tested with node.js 14.15.3 (this might matter for the `require('stream')` test).

**Comment by phated** [comment]
Fwiw, I'd be fine not supporting anything that uses `pump`, as `stream.pipeline`/`readable-stream.pipeline`/`streamx.pipeline` work in subtly different ways than it.

**Comment by coreyfarrell** [comment]
I just posted https://github.com/streamxorg/streamx/issues/40 with a test case directly using `streamx` / `stream` / `readable-stream`.  Though I agree `pump` should no longer be used that's not the issue here.

**Comment by phated** [comment]
@coreyfarrell I'm looking at your streamx issue and the repro is different than when using `lead`, correct? This module is supposed to turn the PassThrough into a Writeable 🤔
